/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client;

import java.io.IOException;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import model.Card;
import model.MatchUser;
import model.Player;
import model.Request;
import model.Response;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author chipc
 */
public class DashBoard extends javax.swing.JFrame {

    Client client;
    private JPanel[] panel = new JPanel[5];
    private JLabel[] ratingLabel = new JLabel[5];
    private JLabel[] imageLabel = new JLabel[15];
    private JButton[] detailButton = new JButton[5];
    private JLabel[] timeLabel = new JLabel[5];

    public DashBoard(Client client) throws ClassNotFoundException, IOException, InterruptedException {
        initComponents();
        this.client = client;
        panel[0] = panel1;
        panel[1] = panel2;
        panel[2] = panel3;
        panel[3] = panel4;
        panel[4] = panel5;
        ratingLabel[0] = rating1;
        ratingLabel[1] = rating2;
        ratingLabel[2] = rating3;
        ratingLabel[3] = rating4;
        ratingLabel[4] = rating5;
        detailButton[0] = detailButton1;
        detailButton[1] = detailButton2;
        detailButton[2] = detailButton3;
        detailButton[3] = detailButton4;
        detailButton[4] = detailButton5;
        imageLabel[0] = image1;
        imageLabel[1] = image2;
        imageLabel[2] = image3;
        imageLabel[3] = image4;
        imageLabel[4] = image5;
        imageLabel[5] = image6;
        imageLabel[6] = image7;
        imageLabel[7] = image8;
        imageLabel[8] = image9;
        imageLabel[9] = image10;
        imageLabel[10] = image11;
        imageLabel[11] = image12;
        imageLabel[12] = image13;
        imageLabel[13] = image14;
        imageLabel[14] = image15;
        timeLabel[0] = time1;
        timeLabel[1] = time2;
        timeLabel[2] = time3;
        timeLabel[3] = time4;
        timeLabel[4] = time5;
        name.setText("Xin chào " + client.getPlayer().getUsername() + "!");
        display();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        panel1 = new javax.swing.JPanel();
        rating1 = new javax.swing.JLabel();
        image1 = new javax.swing.JLabel();
        image2 = new javax.swing.JLabel();
        image3 = new javax.swing.JLabel();
        detailButton1 = new javax.swing.JButton();
        time1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        panel2 = new javax.swing.JPanel();
        rating2 = new javax.swing.JLabel();
        image4 = new javax.swing.JLabel();
        image5 = new javax.swing.JLabel();
        image6 = new javax.swing.JLabel();
        detailButton2 = new javax.swing.JButton();
        time2 = new javax.swing.JLabel();
        panel3 = new javax.swing.JPanel();
        rating3 = new javax.swing.JLabel();
        image7 = new javax.swing.JLabel();
        image8 = new javax.swing.JLabel();
        image9 = new javax.swing.JLabel();
        detailButton3 = new javax.swing.JButton();
        time3 = new javax.swing.JLabel();
        panel4 = new javax.swing.JPanel();
        rating4 = new javax.swing.JLabel();
        image10 = new javax.swing.JLabel();
        image11 = new javax.swing.JLabel();
        image12 = new javax.swing.JLabel();
        detailButton4 = new javax.swing.JButton();
        time4 = new javax.swing.JLabel();
        panel5 = new javax.swing.JPanel();
        rating5 = new javax.swing.JLabel();
        image13 = new javax.swing.JLabel();
        image14 = new javax.swing.JLabel();
        image15 = new javax.swing.JLabel();
        detailButton5 = new javax.swing.JButton();
        time5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Lịch sử đấu");

        rating1.setText("jLabel3");

        image1.setText("jLabel4");

        image2.setText("jLabel5");

        image3.setText("jLabel6");

        detailButton1.setText("Chi tiết");
        detailButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailButton1ActionPerformed(evt);
            }
        });

        time1.setText("jLabel3");

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(rating1)
                .addGap(99, 99, 99)
                .addComponent(image1)
                .addGap(49, 49, 49)
                .addComponent(image2)
                .addGap(60, 60, 60)
                .addComponent(image3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(detailButton1)
                .addGap(41, 41, 41)
                .addComponent(time1)
                .addGap(39, 39, 39))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rating1)
                    .addComponent(image1)
                    .addComponent(image2)
                    .addComponent(image3)
                    .addComponent(detailButton1)
                    .addComponent(time1))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        name.setText("jLabel2");

        rating2.setText("jLabel3");

        image4.setText("jLabel4");

        image5.setText("jLabel5");

        image6.setText("jLabel6");

        detailButton2.setText("Chi tiết");
        detailButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailButton2ActionPerformed(evt);
            }
        });

        time2.setText("jLabel4");

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(rating2)
                .addGap(99, 99, 99)
                .addComponent(image4)
                .addGap(49, 49, 49)
                .addComponent(image5)
                .addGap(60, 60, 60)
                .addComponent(image6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(detailButton2)
                .addGap(40, 40, 40)
                .addComponent(time2)
                .addGap(40, 40, 40))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rating2)
                    .addComponent(image4)
                    .addComponent(image5)
                    .addComponent(image6)
                    .addComponent(detailButton2)
                    .addComponent(time2))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        rating3.setText("jLabel3");

        image7.setText("jLabel4");

        image8.setText("jLabel5");

        image9.setText("jLabel6");

        detailButton3.setText("Chi tiết");

        time3.setText("jLabel5");

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(rating3)
                .addGap(99, 99, 99)
                .addComponent(image7)
                .addGap(49, 49, 49)
                .addComponent(image8)
                .addGap(60, 60, 60)
                .addComponent(image9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                .addComponent(detailButton3)
                .addGap(41, 41, 41)
                .addComponent(time3)
                .addGap(39, 39, 39))
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rating3)
                    .addComponent(image7)
                    .addComponent(image8)
                    .addComponent(image9)
                    .addComponent(detailButton3)
                    .addComponent(time3))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        rating4.setText("jLabel3");

        image10.setText("jLabel4");

        image11.setText("jLabel5");

        image12.setText("jLabel6");

        detailButton4.setText("Chi tiết");

        time4.setText("jLabel6");

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(rating4)
                .addGap(99, 99, 99)
                .addComponent(image10)
                .addGap(49, 49, 49)
                .addComponent(image11)
                .addGap(60, 60, 60)
                .addComponent(image12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(detailButton4)
                .addGap(40, 40, 40)
                .addComponent(time4)
                .addGap(40, 40, 40))
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rating4)
                    .addComponent(image10)
                    .addComponent(image11)
                    .addComponent(image12)
                    .addComponent(detailButton4)
                    .addComponent(time4))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        rating5.setText("jLabel3");

        image13.setText("jLabel4");

        image14.setText("jLabel5");

        image15.setText("jLabel6");

        detailButton5.setText("Chi tiết");

        time5.setText("jLabel7");

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(rating5)
                .addGap(101, 101, 101)
                .addComponent(image13)
                .addGap(49, 49, 49)
                .addComponent(image14)
                .addGap(60, 60, 60)
                .addComponent(image15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(detailButton5)
                .addGap(38, 38, 38)
                .addComponent(time5)
                .addGap(42, 42, 42))
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rating5)
                    .addComponent(image13)
                    .addComponent(image14)
                    .addComponent(image15)
                    .addComponent(detailButton5))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(panel5Layout.createSequentialGroup()
                .addComponent(time5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jButton1.setText("Trở lại");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(253, 253, 253)
                        .addComponent(jLabel1)
                        .addGap(269, 269, 269)
                        .addComponent(name))
                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton1)
                    .addComponent(name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(panel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();

        LobbyView lb = null;

        try {
            lb = new LobbyView(client, client.getPlayer());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
        }
        lb.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void detailButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailButton1ActionPerformed

    private void detailButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_detailButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton detailButton1;
    private javax.swing.JButton detailButton2;
    private javax.swing.JButton detailButton3;
    private javax.swing.JButton detailButton4;
    private javax.swing.JButton detailButton5;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel image10;
    private javax.swing.JLabel image11;
    private javax.swing.JLabel image12;
    private javax.swing.JLabel image13;
    private javax.swing.JLabel image14;
    private javax.swing.JLabel image15;
    private javax.swing.JLabel image2;
    private javax.swing.JLabel image3;
    private javax.swing.JLabel image4;
    private javax.swing.JLabel image5;
    private javax.swing.JLabel image6;
    private javax.swing.JLabel image7;
    private javax.swing.JLabel image8;
    private javax.swing.JLabel image9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel name;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JPanel panel4;
    private javax.swing.JPanel panel5;
    private javax.swing.JLabel rating1;
    private javax.swing.JLabel rating2;
    private javax.swing.JLabel rating3;
    private javax.swing.JLabel rating4;
    private javax.swing.JLabel rating5;
    private javax.swing.JLabel time1;
    private javax.swing.JLabel time2;
    private javax.swing.JLabel time3;
    private javax.swing.JLabel time4;
    private javax.swing.JLabel time5;
    // End of variables declaration//GEN-END:variables

    private void display() throws ClassNotFoundException, IOException, InterruptedException {
        Response res = (Response) client.sendRequest(new Request("GET_MATCHUSER_BY_USER_ID", client.getPlayer().getId()));
        LinkedHashMap<Integer, ArrayList<MatchUser>> list = (LinkedHashMap<Integer, ArrayList<MatchUser>>) res.getPayload(); //comment 
        List<Map.Entry<Integer, ArrayList<MatchUser>>> sortedList = new ArrayList<>(list.entrySet());
        sortedList.sort((entry1, entry2) -> entry2.getKey().compareTo(entry1.getKey()));
        for (int i = 1; i <= 5; i++) {
            if (i <= sortedList.size()) {
                panel[i - 1].setVisible(true);
                Response resRating = (Response) client.sendRequest(new Request("GET_RATINGUSER_BY_MATCH", String.valueOf(client.getPlayer().getId()) + " " + String.valueOf(sortedList.get(i-1).getKey())));
                int rating = (int) resRating.getPayload();
//                System.out.println(client.getPlayer().getId()+" "+rating+" "+String.valueOf(sortedList.get(i-1).getKey()));
                ratingLabel[i - 1].setText("Xếp hạng : " + rating);
                this.revalidate();        // Cập nhật layout
                this.repaint();
                displayImageAndDate(sortedList, sortedList.get(i-1).getKey(), i - 1);
            } else {
                panel[i - 1].setVisible(false);
            }
        }
    }

    public void displayCard(int index, String image) {
        imageLabel[index].setText("");
        ImageIcon icon = new ImageIcon(getClass().getResource(image));
        imageLabel[index].setIcon(icon);
    }

    private void displayImageAndDate(List<Map.Entry<Integer, ArrayList<MatchUser>>> sortedList, int matchId, int index) throws ClassNotFoundException, IOException, InterruptedException {
        String name;
        ArrayList<String> list = new ArrayList<>();
        for (Map.Entry<Integer, ArrayList<MatchUser>> mp : sortedList) {
            if (mp.getKey() == matchId) {
                Timestamp ts = null;
                for (MatchUser mu : mp.getValue()) {
                    ts = mu.getTime();
                    int idCard = mu.getCard_id();
                    Response resCard = (Response) client.sendRequest(new Request("GET_CARD_BY_ID", idCard));
                    Card card = (Card) resCard.getPayload();
                    String value = card.getValue();
                    String image = card.getImage();
                    int word = Character.getNumericValue(value.charAt(0));
                    list.add(image);
                }
                LocalDateTime localDateTime = ts.toLocalDateTime();
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                String formattedTime = localDateTime.format(formatter);
                timeLabel[index].setText(formattedTime);
                detailButton[index].addActionListener(e -> {
                    try {
                        Result result = new Result(this, true, client, matchId);
                    } catch (ClassNotFoundException ex) {
                        Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (IOException ex) {
                        Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(DashBoard.class.getName()).log(Level.SEVERE, null, ex);
                    }
                });
            }
        }
        for (int i = 0; i < list.size(); i++) {
            displayCard(index * 3 + i, list.get(i));
        }

        //hien thi thoi gian : 
    }
}
