/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package client;

import java.awt.event.ActionEvent;
import java.io.IOException;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JOptionPane;
import model.Player;
import model.Request;
import model.Response;

/**
 *
 * @author chipc
 */
public class LoginView extends javax.swing.JFrame {
    private Client client;
   public LoginView(Client client) {
        this.client = client;
        this.setTitle("Login");
        initComponents();
        this.setLocationRelativeTo(null);// Khởi tạo các thành phần giao diện
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        passwordField = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ĐĂNG NHẬP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 110, 160, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tài khoản : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 90, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Mật khẩu : ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, -1, -1));
        getContentPane().add(usernameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 202, 270, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Đăng nhập");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 160, 40));
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 282, 270, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\assets\\ltmang\\ver3\\testServer\\src\\asset\\image\\tett.jpg")); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -360, 1050, 880));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            loginButtonActionPerformed(evt);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void close() {
          this.dispose();
        }
        public void display(){
            this.setVisible(true);
        }
    /**
     * @param args the command line arguments
     */
    private void loginButtonActionPerformed(ActionEvent evt) throws IOException, InterruptedException {
        String username = usernameField.getText().trim();
        String password = new String(passwordField.getPassword()).trim(); // Lấy mật khẩu từ JPasswordField
        String[] payload = {username, password};
        try {
            Response response = (Response) client.sendRequest(new Request("LOGIN", payload));
            if (response.getPayload() instanceof Player) {
                Player player = (Player) response.getPayload();
                if (player == null) {
                    JOptionPane.showMessageDialog(this, "Bạn đã nhập sai tài khoản hoặc mật khẩu!");
                } else {
//                    JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
                    client.setPlayer(player);
                    LobbyView lobbyView = new LobbyView(client, player); // Mở LobbyViewForm mới
                    this.dispose(); // Đóng LoginViewForm
                    lobbyView.setVisible(true);
                    client.setLobbyView(lobbyView);
                }
            } else if(response.getPayload() instanceof String) {
                JOptionPane.showMessageDialog(this, "Tài khoản này đã được đăng nhập chỗ khác , vui lòng thử lại sau !");
            }else {
                JOptionPane.showMessageDialog(this, "Bạn đã nhập sai tài khoản hoặc mật khẩu!");
            }
        } catch (ClassNotFoundException | IOException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField usernameField;
    // End of variables declaration//GEN-END:variables
}
